
name: Release for my_shell

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        cd ./my_shell
        python -m pip install --upgrade pip
        poetry install
    - name: Build package
      run: |
        cd ./my_shell
        poetry build
    - name: Publish to PyPI
      run: |
        cd ./my_shell
        python -m pip install twine
        poetry publish --build
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./my_shell
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/my-shell:${{ github.ref_name }}
        platforms: linux/amd64,linux/arm64
